services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # UI
      - "5672:5672"    # AMQP
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  krakend:
    image: devopsfaith/krakend
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - fastapi
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge